---
name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: "Get pip cache dir"
        id: "pip-cache"
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: "Cache pip packages"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.pip-cache.outputs.dir }}"
          key: "${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Install requirements"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run build test"
        run: |
          make test
  lint:
    name: "Linting"
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-python@v5"
    - uses: "pre-commit/action@v3.0.1"
---
name: "Monthly linkcheck"
on:
  schedule:
    - cron: "0 0 11 * *"
  workflow_dispatch:
jobs:
  test:
    name: "Monthly linkcheck"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Linkcheck"
        run: |
          make linkcheck
