---
name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-18.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
      - name: "Install requirements"
        run: |
          pip install -r requirements.txt
      - name: "Run build test"
        run: |
          make test
